### ISSUE TITLE
Selecting

### ISSUE THREAD

**Issue by NouraldinS** [FACG4/abhi-team#35]
```css
h2 {
  font-size: 30px;
  /* word-break: break-all; */
}
```
Be most specific when selecting your html elements in your css, you don't want your code to overlap with your teammates.

**Comment by NouraldinS** [comment]
```css
img {
  border-style: solid;
  border-width: 1px;
}
```
same deal
