### ISSUE TITLE
normalize.css

### ISSUE THREAD

**Issue by NouraldinS** [FACG4/abhi-team#42]
What's the point of normalize.css?
override everything browsers give?
take this
```css
* {
margin: 0;
padding: 0;
}
```
that's mostly everything you'll be needing to 'normalize' your CSS.
